/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AnalyzeMatch: typeof import('./components/AnalyzeMatch.vue')['default']
    AnalyzeTeam: typeof import('./components/AnalyzeTeam.vue')['default']
    AnniversaryAnnouncement: typeof import('./components/AnniversaryAnnouncement.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BracketBoard: typeof import('./components/bracket/BracketBoard.vue')['default']
    BracketColumn: typeof import('./components/bracket/BracketColumn.vue')['default']
    BracketConnectors: typeof import('./components/bracket/BracketConnectors.vue')['default']
    BracketInfoCard: typeof import('./components/bracket/BracketInfoCard.vue')['default']
    BracketMatchCard: typeof import('./components/bracket/BracketMatchCard.vue')['default']
    BracketPage: typeof import('./components/BracketPage.vue')['default']
    BracketTeamRow: typeof import('./components/bracket/BracketTeamRow.vue')['default']
    CompleteFormRank: typeof import('./components/CompleteFormRank.vue')['default']
    ForecastPoster: typeof import('./components/ForecastPoster.vue')['default']
    GraphComment: typeof import('./components/GraphComment.vue')['default']
    GroupMatchData: typeof import('./components/GroupMatchData.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HistoryMatch: typeof import('./components/HistoryMatch.vue')['default']
    MatchGraph: typeof import('./components/MatchGraph.vue')['default']
    MatchMenu: typeof import('./components/MatchMenu.vue')['default']
    MatchRecord: typeof import('./components/MatchRecord.vue')['default']
    RobotDataProgress: typeof import('./components/RobotDataProgress.vue')['default']
    RobotDataRadar: typeof import('./components/RobotDataRadar.vue')['default']
    RobotDataTable: typeof import('./components/RobotDataTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPlayer: typeof import('./components/SearchPlayer.vue')['default']
    Situation: typeof import('./components/Situation.vue')['default']
    StageRangeSelector: typeof import('./components/StageRangeSelector.vue')['default']
    TeamHeader: typeof import('./components/TeamHeader.vue')['default']
    UpdateAnnouncement: typeof import('./components/UpdateAnnouncement.vue')['default']
  }
}
