/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MatchesNode: typeof import('./components/MatchesNode.vue')['default']
    MatchGraph: typeof import('./components/MatchGraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Situation: typeof import('./components/Situation.vue')['default']
    SwissWheel: typeof import('./components/MatchGraph.vue')['default']
  }
}
